### ISSUE TITLE
OpenJDK version breaks build

### ISSUE THREAD

**Issue by jtravell** [Dwolla/atlassian-crowd-docker#5]
When I type `docker build -t nameOfImageToBeBuilt .` in the root directory of the code from this GitHub repo, I get the following error:

    ERROR: unsatisfiable constraints:
      openjdk8-8.171.11-r0:
        breaks: world[openjdk8=8.151.12-r0]
  
>**What specific changes need to be made to the code from this repo in order for the OpenJDK version to stop causing this error?**

**Comment by dmunney** [comment]
It appears that tomcat changed their version scheme for the base image.  Give this new one a try.
